pipeline:
  name: raghu-terraform-dyinv
  identifier: raghuterraformdyinv
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dynamic
        identifier: dynamic
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: harnesswsraghu
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
        tags: {}
    - stage:
        name: an
        identifier: an
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          #!/bin/bash
                          set -e

                          echo "===== STEP 1: Update system ====="
                          apt-get update -y

                          echo "===== STEP 2: Install Ansible ====="
                          apt-get install -y ansible

                          echo "===== STEP 3: Verify repo structure ====="
                          pwd
                          ls

                          echo "===== STEP 4: Go to ansible directory ====="
                          cd ansible
                          ls

                          echo "===== STEP 5: Test dynamic inventory (NO SSH) ====="
                          ansible-inventory -i inventory/gcp.yml --graph

                          echo "===== STEP 6: Install Apache using Ansible ====="
                          ansible-playbook -i inventory/gcp.yml playbooks/install-apache.yml

                          echo "===== DONE: Apache installation completed ====="
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
